import '../styles/globals.css'
import Head from 'next/head'

/*
En este componente importamos los estilos y cosas que concierne a toda la app,
como por ejemplo el Header.
*/
function MyApp({ Component, pageProps }) {

  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </>
}

export default MyApp
